CREATE TABLE PUBLIC.T_USER(
    ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(255) not null,
    LAST_NAME VARCHAR(255) not null
);            
ALTER TABLE PUBLIC.T_USER ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);


CREATE TABLE PUBLIC.T_ACCOUNT(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    BALANCE DECIMAL(20, 2),
    USER_ID BIGINT
);            
ALTER TABLE PUBLIC.T_ACCOUNT ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);

CREATE SEQUENCE PUBLIC.FINANCE_SEQUENCE START WITH 100;